Restaurant/Restaurant/Controllers/CartController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

using Restaurant.Helper;
using Restaurant.Models;
using Restaurant.Repositories;
using Restaurant.ViewModels.CartViewModel;

namespace Restaurant.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IGenericRepository<Product> _product;
        private readonly IGenericRepository<OrderItems> _orderItems;
        private readonly IGenericRepository<Customer> _customer;
        private readonly IGenericRepository<Order> _customerOrder;
        //private readonly RestaurantContext _context;
        private readonly IMapper _mapper;
        public CartController(IGenericRepository<Product> productRepository, IGenericRepository<OrderItems> orderItemsRepository, IGenericRepository<Customer> customerRepository, IGenericRepository<Order> orderRepository, IMapper mapper, /*RestaurantContext context,*/ UserManager<ApplicationUser> userManager)
        {
            _product = productRepository;
            _orderItems = orderItemsRepository;
            _customer = customerRepository;
            _customerOrder = orderRepository;
            _mapper = mapper;
            //_context = context;
            _userManager = userManager;
        }



        // GET: /Cart/AddtoCart
        // get related cart info for specific customer
        public IActionResult AddToCart(int id, int quantity)
        {
            // check if user authenticated or not
            // inherit User_property from controller_Base
            //this property it's getMethod, so don't assigned value to it..
            bool user = User.Identity.IsAuthenticated;

            var addedProduct = _product.GetByID(id);

            if (addedProduct == null)
            {
                // output msg: try again
                return RedirectToAction("Index", "Home");
            }


            var mappedProduct = _mapper.Map<CartItemViewModel>(addedProduct);
            mappedProduct.Quantity = quantity;

            // save cart item to session
            HttpContext.Session.Set("CartItem", mappedProduct);

            return RedirectToAction("Index", "Home");

        }

        // GET: /Cart/Checkout
        [HttpGet]
        public IActionResult Checkout()
        {
            // get and deserialize data json
            var cartItem = HttpContext.Session.Get<CartItemViewModel>("CartItem");

            return View(cartItem);
        }

        public IActionResult PlaceOrder()
        {
            var user = _userManager.GetUserAsync(User);
            var mockUserId = 1;

            // get and deserialize data json
            var cartItem = HttpContext.Session.Get<CartItemViewModel>("CartItem");


            var customerOrder = new Order
            {
                CustomerID = mockUserId,
                TotalPrice = cartItem.ItemsTotalPrice,
                PlacedAt = DateTime.UtcNow,
            };

            // Add the customer order to the database
            _customerOrder.Insert(customerOrder);

            // create order item accordingly
            var orderItem = new OrderItems
            {
                OrderID = customerOrder.ID,
                ProductID = cartItem.Id,
                Quantity = cartItem.Quantity,
                Price = cartItem.Price
            };

            // check if sufficient quantity avaiable or possible null
            if (orderItem == null || orderItem.Quantity == 0  /*||cartItem.Quantity > orderItem.Quantity*/)
            {
                ViewBag.NotAvailable = "There is not enough quantity in the store at the moment, try another time!";
                return View();
            }


            _orderItems.Insert(orderItem);

            //_context.SaveChanges();

            return View();
        }
    }
}

Restaurant/Restaurant/Controllers/ProductsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

using Restaurant.Helper;
using Restaurant.Models;
using Restaurant.Repositories;
using Restaurant.ViewModels.ProductViewModel;

namespace Restaurant.Controllers
{
    [Authorize(Roles ="Admin")]
    public class ProductsController : Controller
    {
        private readonly IGenericRepository<Category> _category;

        private readonly IGenericRepository<Product> _product;

        RestaurantContext _context;
        private IMapper _mapper;

        // upload img
        //private readonly FileUploader _fileUpload;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ProductsController(IGenericRepository<Product> product, IMapper mapper, IGenericRepository<Category> category, /*FileUploader fileUpload,*/ IWebHostEnvironment webHostEnvironment, RestaurantContext context)
        {
            _product = product;
            _mapper = mapper;
            _category = category;
            //_fileUpload = fileUpload;
            _webHostEnvironment = webHostEnvironment;
            _context = context;
        }


        // GET: ProductsController 
        //[Authorize] // check cookie expired or not ??
        public IActionResult Index()
        {
            var products = _product.GetAll();

            var mappedProducts = _mapper.Map<IEnumerable<ProductListViewModel>>(products);

            if (mappedProducts == null) return NotFound();
            foreach (var product in mappedProducts)
            {
                var category = _category.Find(c => c.ID == product.CategoryID).FirstOrDefault();
                product.Category = category?.Name;
            }

            // render UI
            return View(mappedProducts);
        }



        // GET: Product/Create
        [HttpGet]
        public IActionResult Create()
        {
            var vm = new ProductViewModel();

            var categories = _category.GetAll();

            // populate list for select html view
            ViewBag.CategoriesList = new SelectList(categories, "ID", "Name");
            ViewBag.Categories = categories;
            return View(vm);
        }


        // POST: Product/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ProductViewModel vm)
        {
            //    //// for image upload
            //FileUploader fileupload = new FileUploader(_webHostEnvironment);
            //string imgFileName = fileupload.Upload(vm.Image);

            // get the choose category from user form
            var choosenCategory = _category.Find(c => c.ID == vm.CategoryID).FirstOrDefault();

            if (ModelState.IsValid)
            {
                // map view model data from user into a record
                var newProduct = _mapper.Map<Product>(vm);

                try
                {
                    // update db records for products
                    _product.Insert(newProduct);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, "Error occured during insertdatabase, please try again: " + ex.Message);

                    return View(vm);

                }
            }
            // unexpected err
            return RedirectToAction(nameof(Index));
        }


        // GET: ProductsController/Edit/5
        public IActionResult Edit([FromRoute] int id)
        {

            var product = _product.GetByID(id);
            if (product == null)
            {
                return NotFound();
            }

            // get the model out of the record
            var productViewModel = _mapper.Map<ProductViewModel>(product);

            var categories = _category.GetAll();

            //// update categories into the view
            //productViewModel.Categories = categories;

            // populate list for select html view
            ViewBag.CategoriesList = new SelectList(categories, "ID", "Name");
            ViewBag.Categories = categories;

            return View(productViewModel);
        }

        // POST: ProductsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, ProductViewModel vm)
        {

            if (ModelState.IsValid)
            {
                //var product = _mapper.Map<Product>(ProductViewModel);

                var product = _product.GetByID(id);

                var chosenCategory = _category.Find(c => c.ID == vm.CategoryID).FirstOrDefault();
                //product.Category = chosenCategory;


                try
                {
                    // to refactor to product repository
                    product.Price = vm.Price;
                    product.Title = vm.Title;
                    product.Category = chosenCategory;
                    // apply change to db
                    _context.SaveChanges();
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, "Error occured during updating the database, please try again: " + ex.Message);

                    return View(vm);
                }

                return RedirectToAction(nameof(Index));
            }

            // unexpected err
            return RedirectToAction(nameof(Index));
        }

        // Post: ProductsController/Delete/5

        [HttpGet]
        public IActionResult Delete(int id, ProductViewModel vm)
        {
            var product = _product.GetByID(id);

            if (product != null)
            {
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            try
            {
                // delete the product
                _product.Delete(id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                throw new Exception("Err occured during deleting the product record: " + ex.Message);
            }

        }

        
    }
}

Restaurant/Restaurant/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Restaurant</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Restaurant.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Restaurant</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Restaurant - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Restaurant/Restaurant/Views/Shared/_RestaurantLayOut.cshtml
<!DOCTYPE html>
<html>
<head>
    <!-- Basic -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Mobile Metas -->
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- fontawsem  css -->

    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
          integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer" />
    <!-- Site Metas -->
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <link rel="shortcut icon" href="/images/favicon.png" type="" />

    <title>INFINITY</title>

    <!-- bootstrap core css -->
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.css" />

    <!--owl slider stylesheet -->
    <link rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
    <!-- nice select  -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/css/nice-select.min.css"
          integrity="sha512-CruCP+TD3yXzlvvijET8wV5WxxEh5H8P4cmz0RFbKK6FlZ2sYl3AEsKlLPHbniXKSrDdFewhbmBK5skbdsASbQ=="
          crossorigin="anonymous" />
    <!-- font awesome style -->
    <link href="/css/font-awesome.min.css" rel="stylesheet" />

    <!-- Custom styles for this template -->
    <link href="/css/style.css" rel="stylesheet" />
    <!-- responsive style -->
    <link href="/css/responsive.css" rel="stylesheet" />
</head>

<body>
    <div class="hero_area">
        <!-- <div class="bg-box">
          <img src="images/hero-bg.jpg" alt="" />
        </div> -->
        <!-- header section strats -->
        <!-- <div class="overlay"> -->
        <header class="header_section">
            <div class="container">
                <nav class="navbar navbar-expand-lg custom_nav-container">
                    <a class="navbar-brand" asp-action="Index" asp-controller="Home">
                        <span class="d-flex">
                            <img src="./images/infint.png" alt="" style="width: 100px" />
                            <p>Infinity</p>
                        </span>
                    </a>

                    <button class="navbar-toggler"
                            type="button"
                            data-toggle="collapse"
                            data-target="#navbarSupportedContent"
                            aria-controls="navbarSupportedContent"
                            aria-expanded="false"
                            aria-label="Toggle navigation">
                        <span class=""> </span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav mx-auto">
                            <li class="nav-item active">
                                <a class="nav-link" asp-action="Index" asp-controller="Home">Menu
                                    <span class="sr-only">(current)</span></a>
                            </li>

                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-action="Index" asp-controller="Products">Products</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-action="Index" asp-controller="ProductCategories">Categories</a>
                                </li>
                            } 

                            @if (User.Identity.IsAuthenticated == false)
                            {
                                // this icon is a registration 
                                <li class="nav-item">
                                    <div class="dropdown " style="background-color: transparent; border: 1px solid #fff; border-radius: 6px;">
                                        <a class="nav-link  role="button" asp-action="CustomerRegister" asp-controller="Account">
                                            Register
                                        </a>
                                    </div>
                                </li>
                            }

                            @if (User.Identity.IsAuthenticated == true)
                            {
                                <li class="nav-item">
                                    <a class="nav-link" >Welcome @User.Identity.Name</a>
                                </li>

                                @*<li class="nav-item">
                                    <div class="dropdown " style="background-color:darkblue; border: 1px solid darkblue; border-radius: 6px;">
                                        <a class="nav-link text-light role="button" asp-action="AdminRegister" asp-controller="Account">
                                            Upgrade your account 
                                        </a>
                                    </div>
                                </li>*@
                                
                            }

                        </ul>
                        <div class="user_option ">
                             @if (User.Identity.IsAuthenticated == true)
                            {
                                <a class="cart_link" asp-action="Checkout" asp-controller="Cart">
                                    <i class="fa-solid fa-cart-shopping"></i>
                                </a>
                            }
                            
                            @using (Html.BeginForm("SearchProduct", "Home", FormMethod.Get))
                            {
                                @Html.TextBox("Seacrchname", null, new { @style="width: 60%;"})
                                <button class="btn my-2 my-sm-0 nav_search-btn" type="submit">
                                    <i class="fa fa-search" aria-hidden="true"></i>
                                </button>
                            }
                                
                            
                            @if (User.Identity.IsAuthenticated == false)
                            {
                                <a asp-action="Login" asp-controller="Account" class="order_online"> LogIn  </a>
                            }
                            else 
                            {
                                <a asp-action="Signout" asp-controller="Account" class="order_online"> LogOut  </a>
                            }
                        </div>
                    </div>
                </nav>
            </div>
            <!-- </div> -->
        </header>
     
        @RenderBody()
 
    </div>

    <!-- offer section -->
    <!-- end offer section -->
    <!-- about section -->


    <!-- end about section -->
    <!-- client section -->
    <!-- end client section -->
    <!-- footer section -->
    <footer class="footer_section">
        <div class="container">
            <div class="row">
                <div class="col-md-4 footer-col">
                    <div class="footer_contact">
                        <h4>Contact Us</h4>
                        <div class="contact_link_box">
                            <a href="">
                                <i class="fa fa-map-marker" aria-hidden="true"></i>
                                <span> Location </span>
                            </a>
                            <a href="">
                                <i class="fa fa-phone" aria-hidden="true"></i>
                                <span> Call +01 1234567890 </span>
                            </a>
                            <a href="">
                                <i class="fa fa-envelope" aria-hidden="true"></i>
                                <span> demo@gmail.com </span>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 footer-col">
                    <div class="footer_detail">
                        <a href="" class="footer-logo"> Feane </a>
                        <p>
                            Necessary, making this the first true generator on the Internet.
                            It uses a dictionary of over 200 Latin words, combined with
                        </p>
                        <div class="footer_social">
                            <a href="">
                                <i class="fa fa-facebook" aria-hidden="true"></i>
                            </a>
                            <a href="">
                                <i class="fa fa-twitter" aria-hidden="true"></i>
                            </a>
                            <a href="">
                                <i class="fa fa-linkedin" aria-hidden="true"></i>
                            </a>
                            <a href="">
                                <i class="fa fa-instagram" aria-hidden="true"></i>
                            </a>
                            <a href="">
                                <i class="fa fa-pinterest" aria-hidden="true"></i>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 footer-col">
                    <h4>Opening Hours</h4>
                    <p>Everyday</p>
                    <p>10.00 Am -10.00 Pm</p>
                </div>
            </div>
            <div class="footer-info">
                <p>
                    &copy; <span id="displayYear"></span> All Rights Reserved By
                    <a href="https://html.design/">Free Html Templates</a><br /><br />
                    &copy; <span id="displayYear"></span> Distributed By
                    <a href="https://themewagon.com/" target="_blank">ThemeWagon</a>
                </p>
            </div>
        </div>
   
    </footer>
    <!-- footer section -->
    <!-- jQery -->
    <script src="js/jquery-3.4.1.min.js"></script>
    <!-- popper js -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <!-- bootstrap js -->
    <script src="js/bootstrap.js"></script>
    <!-- owl slider -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
    <!-- isotope js -->
    <script src="https://unpkg.com/isotope-layout@3.0.4/dist/isotope.pkgd.min.js"></script>
    <!-- nice select -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/js/jquery.nice-select.min.js"></script>
    <!-- custom js -->
    <script src="js/custom.js"></script>
    <!-- Google Map -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap"></script>
    <!-- End Google Map -->
    @RenderSection("Scripts", false);
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</body>
</html>